/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesTicTacToeRouteImport } from './routes/games/tic-tac-toe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesTicTacToeRoute = GamesTicTacToeRouteImport.update({
  id: '/games/tic-tac-toe',
  path: '/games/tic-tac-toe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/tic-tac-toe': typeof GamesTicTacToeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/tic-tac-toe': typeof GamesTicTacToeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/tic-tac-toe': typeof GamesTicTacToeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/tic-tac-toe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/tic-tac-toe'
  id: '__root__' | '/' | '/games/tic-tac-toe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesTicTacToeRoute: typeof GamesTicTacToeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/tic-tac-toe': {
      id: '/games/tic-tac-toe'
      path: '/games/tic-tac-toe'
      fullPath: '/games/tic-tac-toe'
      preLoaderRoute: typeof GamesTicTacToeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesTicTacToeRoute: GamesTicTacToeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
